stages:
  - build
  - deploy

build-check:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - earthly +build

package-all:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - earthly +all
  artifacts:
    paths:
      - build/libniven*.deb

deploy-packages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  needs: [ package-all ]
  script:
    - scp build/*.deb $DEPLOY_DOWNLOADS/libniven/

deploy-phi:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  needs: [ package-all ]
  script:
    - phi-deploy build/libniven0*~bionic_amd64.deb bionic oss
    - phi-deploy build/libniven0*~focal_amd64.deb focal oss
