stages:
  - build
  - deploy

build-check:
  image: emergent:xenial
  stage: build
  only:
    - master
  before_script:
    - dpkg -i
      /packages/xenial/oss/libemergent-dev.deb
      /packages/xenial/oss/libentity-dev.deb
  script:
    - premake5 gmake
    - make -j4

package-xenial:
  image: emergent:xenial
  stage: build
  only:
    - tags
  before_script:
    - dpkg -i
      /packages/xenial/oss/libemergent-dev.deb
      /packages/xenial/oss/libentity-dev.deb
  script:
    - premake5 gmake
    - make -j4 libniven
    - cd packages
    - ./build
    - mkdir -p /packages/xenial/oss/
    - cp libniven-dev_*.deb /packages/xenial/oss/libniven-dev.deb
    - cp libniven0_*.deb /packages/xenial/oss/libniven0.deb
  artifacts:
    paths:
      - packages/*.deb

deploy-packages:
  image: emergent:deploy
  stage: deploy
  when: on_success
  only:
    - tags
  dependencies:
    - package-xenial
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - cd packages
    - scp *.deb jenkins@downloads.emergent-design.co.uk:/srv/downloads/libniven/
