include:
  - project: 'core/common'
    file: '/templates/ci.yml'

variables:
  COMPONENT: oss

package-niven:
  extends: [ .build-packages ]
  variables: { MODULE: niven, MATCH: /^v.*$/ }

deploy-niven:
  needs: [ package-niven ]
  extends: [ .deploy-packages ]
  variables: { MODULE: niven, MATCH: /^v.*$/  }
