stages:
  - build
  - deploy

build-check:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - earthly +build

package-all:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - earthly +all
  artifacts:
    paths:
      - build/libniven*.deb

deploy-packages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  needs: [ package-all ]
  script:
    - scp build/*.deb $DEPLOY_DOWNLOADS/libniven/
    - for REPO in bionic focal; do
        phi-deploy build/libniven0*~$REPO_amd64.deb $REPO oss;
        phi-deploy build/libniven-dev*~$REPO_amd64.deb $REPO oss;
      done
