stages:
  - build
  - deploy

build-check:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - earthly +build

package-all:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - earthly +all
  artifacts:
    paths:
      - build/**.deb

deploy-packages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  needs: [ package-all ]
  script:
    - for REPO in bionic focal; do
        for ARCH in amd64 arm64; do
          phi-deploy build/libniven0*~${REPO}_${ARCH}.deb $REPO oss;
          phi-deploy build/libniven-dev*~${REPO}_${ARCH}.deb $REPO oss;
        done
      done
