name: CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
          
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.8.15
          
      - uses: actions/checkout@v4
         
      - name: Run build
        run: earthly +all

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/**/*.deb
